DROP table warehouses ;
DROP table design;
DROP table product;
DROP table raw_materials;
DROP table machines;

DROP TABLE EMPLOYEES;
DROP TABLE POSITION_A;
DROP TABLE DEP;
DROP TABLE SUPPLIER;

CREATE TABLE POSITION_A(
POS_ID NUMBER (15)NOT NULL,
MANGER_POS_ID NUMBER (15),
POS_NAME VARCHAR(20)NOT NULL,
CONSTRAINT POS_ID_PK PRIMARY KEY(POS_ID),
CONSTRAINT MANGER_ID_FK FOREIGN KEY (MANGER_POS_ID)REFERENCES POSITION_A(POS_ID)
);

CREATE TABLE DEP(
DEP_ID NUMBER (15)NOT NULL,
BEP_NAME VARCHAR(20)NOT NULL,
CONSTRAINT DEP_ID_PK PRIMARY KEY (DEP_ID)
);

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER (15)NOT NULL,
POSI_ID NUMBER(15)NOT NULL,
DEPA_ID NUMBER (15)NOT NULL,
EMP_NAME VARCHAR(20) NOT NULL,
APSENCE_PER_WEEK NUMBER (3),
BIRTH_DATE DATE,
SALARY NUMBER (10),
NATIONAL_ID NUMBER (14)NOT NULL UNIQUE,
CONSTRAINT EMPLOYEES_PK PRIMARY KEY (EMPLOYEE_ID),
CONSTRAINT POS_ID_FK FOREIGN KEY(POSI_ID) REFERENCES POSITION_A(POS_ID) ,
CONSTRAINT DEP_ID_FK FOREIGN KEY (DEPA_ID)REFERENCES DEP(DEP_ID)
);


CREATE TABLE GOV(
tax_code number(9)not null,
EMP_ID number(15)not null,
CONSTRAINT gov_PK PRIMARY KEY (tax_code),
CONSTRAINT EMPLOYEE_ID_FK FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);





CREATE table warehouses(
wh_code_ID NUMBER(15) PRIMARY KEY ,
wh_capacity NUMBER(15),
phone NUMBER(15),
address VARCHAR(15)
);
CREATE table design(
design_ID NUMBER(15) PRIMARY KEY ,
year NUMBER(4),
season VARCHAR(15),
wh_code_ID NUMBER(15),
FOREIGN KEY(wh_code_ID)REFERENCES warehouses(wh_code_ID)
);
CREATE TABLE product(
prod_ID NUMBER(15),
p_type VARCHAR(15),
colour VARCHAR(15),
p_size VARCHAR(15),
season VARCHAR(15),
wh_code_ID NUMBER(15),
design_ID NUMBER(15),
FOREIGN KEY(wh_code_ID)REFERENCES warehouses(wh_code_ID),
FOREIGN KEY(design_ID)REFERENCES design(design_ID)
);
CREATE TABLE machines(
machine_code NUMBER(15) PRIMARY KEY,
material_type VARCHAR(15),
regular_maintenance VARCHAR(15),
quantity_of_machines VARCHAR(15)
);
CREATE TABLE SUPPLIER(
SHIPMENT_ID NUMBER(15)NOT NULL,
EMPL_ID NUMBER(15)NOT NULL,
CONSTRAINT SHIPMENT_ID_PK PRIMARY KEY (SHIPMENT_ID),
CONSTRAINT EMP_FK FOREIGN KEY (EMPL_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID)
);
CREATE TABLE raw_materials(
raw_code NUMBER(15) PRIMARY KEY,
wh_code_ID NUMBER(15),
quantity VARCHAR(15),
price NUMBER(15),
r_type VARCHAR(15),
machine_code NUMBER(15),
SHIPMENT_ID NUMBER(15),
FOREIGN KEY(wh_code_ID)REFERENCES warehouses(wh_code_ID),
FOREIGN KEY(machine_code)REFERENCES machines(machine_code),
FOREIGN KEY(SHIPMENT_ID)REFERENCES SUPPLIER(SHIPMENT_ID)
);

